### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by ethever** [remkop22/rusqlite-from-row#1]
https://github.com/remkop22/rusqlite-from-row/blob/14a3c9f61473ffdbfa5693a1bf73d8b5fa8ed3b1/Cargo.toml#LL6C1-L13C29

missing `version` in `Cargo.toml`

**Comment by remkop22** [comment]
Hi @ethever 

I'm not sure why it's not compiling on your machine.

This crate uses [cargo workspace inheritance](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) to declare it's version like `version.workspace = true`. The actual version is declared under `[workspace.package]`.

What version of rust/cargo are you using?

**Comment by ethever** [comment]
Sorry for the stupid question. I have figured it out. Thanks for reply.

>
